######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 24 20:20:52 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += painting.cpp
